### PR TITLE
corrected Windows installation verification step instructions

### PR DESCRIPTION
**Pull request by maxvol**
corrected Windows installation verification step instructions as discussed here -
https://github.com/tensorflow/swift/issues/421

### CODE REVIEW

**Comment by ematejska** [comment]
@maxvol Could you please sign the CLA?

**Comment by maxvol** [comment]
> @maxvol Could you please sign the CLA?

done! sorry for delay

**Comment by maxvol** [comment]
@googlebot I signed it!

**Comment by ematejska** [comment]
The page now needs to take into consideration all platforms.

**Comment by dabrahams** [comment]
@compnerd PTAL.  Should we change the prompt character from `$` to `>`?

**Comment by compnerd** [comment]
I think that fixing the prompt character can be done in a follow up as it was incorrect before this.

**Comment by compnerd** [comment]
Thanks @maxvol for the improvements!

**Pull request merged**
