### PR TITLE
Update TensorFlow logo in README

### PR DESCRIPTION
**Pull request by 8bitmp3**
Hey @dan-zheng I noticed your PR here https://github.com/tensorflow/swift/pull/261 and maybe this could help. I did a S4TF presentation locally, so I had a logo saved on my machine and it gave me an idea. Sorry, don't know if you can merge the PRs to avoid duplication 🤔

The only diff is the TensorFlow logo. Methodology: used a high res "new TensorFlow" logo .png file, shrunk it to match the height of Swift's existing logo, placed it on top of the old TensorFlow logo.

Any questions @dan-zheng @rxwei @MarkDaoust, let me know.

### CODE REVIEW

**Comment by 8bitmp3** [comment]
@googlebot I fixed it.

**Comment by 8bitmp3** [comment]
> @googlebot I fixed it.

If there is a manual way to check CLA let me know @googlebot 🤖 I've re-committed after resetting credentials and still get the same error 🤷‍♀️

**Comment by 8bitmp3** [comment]
> Thanks for the patch! The distance between the right boarder of the Swift logo and the plus sign is 54 pixels, but it's 49 pixels from from the plus sign to the left boarder of the TensorFlow logo. Could you update the logo so that the distance is 54 pixels on both sides?

@rxwei Good catch. 🦅👁 I took the original white background, added the original plus sign, as well as resized transparent Swift and TF logos as layers. Then, I used the old coordinates to move the logos in the right positions. The TensorFlow logo should start at 266 (x-axis) from 212 (x-axis) where the + sign "ends". The diff is 54 pixels, as requested.

image

I'm not a graphics designer by the way ✌️Let me know if anything else needs to be polished 🧹 @dan-zheng @rxwei

**Comment by 8bitmp3** [comment]
@googlebot I fixed it.

**Comment by 8bitmp3** [comment]
> @googlebot I fixed it.

hi @willnorris found you via https://github.com/tensorflow/tensorboard/issues/508 can you take a look at this CLA issue. the last (and only one that should be ok) passed the CLA checks—it was done via github's web client. previous remote "git push"s didn't register as mine. thanks!

**Comment by willnorris** [comment]
It's still tripping up on the older commits.  Squash things down to a single commit with the right author information and that should fix the CLA check.

**Comment by 8bitmp3** [comment]
Thanks @willnorris Rebasing and fixing git config should've fixed it, @8bitmp3 is such an amateur.

@rxwei re-submitted 1 commit to pass the CLA check. take a look 👍 thank you

**Pull request merged**
