### PR TITLE
Update README.md with some comments from https://github.com/tensorflow/swift/issues/370

### PR DESCRIPTION
**Pull request by migueldeicaza**
This brings a couple of links that showed up in this discussion:

https://github.com/tensorflow/swift/issues/370

### CODE REVIEW

**Comment by migueldeicaza** [comment]
I do not mind.

**Comment by dan-zheng** [comment]
Hi @migueldeicaza: could you please sign https://cla.developers.google.com? Contributors must sign the CLA before their PRs can be merged.

Please see the comment by @googlebot above for more info!

**Comment by texasmichelle** [comment]
Reminder to sign the CLA so that this can be merged.

**Comment by migueldeicaza** [comment]
@googlebot I signed it

**Pull request merged**
